com.influxdb.exceptions.UnprocessableEntityException: HTTP status code: 422; Message: failure writing points to database: partial write: field type conflict: input field "ServiceCron.StatisticUploader.sendToInflux" on measurement "ServicePromise" is type integer, already exists as type float dropped=45